### PR TITLE
Cache token

### PR DESCRIPTION
**Pull request by rgbkrk**
This caches tokens directly.

I'm not sure how to use a token in a fail-safe way that would try to reach the service using the cached token, and if it fails, gets a new token from identity.

### CODE REVIEW

**Comment by rgbkrk** [comment]
@smashwilson any ideas about how we could update the tokens on a failed call with our current layout?

**Comment by rgbkrk** [comment]
Nevermind, think I've got this with a light `HEAD` request.

**Comment by rgbkrk** [comment]
```
$ time ./carina list --cache
ClusterName         Flavor              Nodes               AutoScale           Status
awaywego            container1-4G       1                   false               active
clibuilder          container1-4G       1                   false               active
test                container1-4G       1                   false               active

real    0m1.537s
user    0m0.057s
sys 0m0.080s
$ time ./carina list --no-cache
ClusterName         Flavor              Nodes               AutoScale           Status
awaywego            container1-4G       1                   false               active
clibuilder          container1-4G       1                   false               active
test                container1-4G       1                   false               active

real    0m2.366s
user    0m0.073s
sys 0m0.156s
```

**Comment by rgbkrk** [comment]
Shaving off a little under a second (when requesting from here in Japan). :wink:

**Comment by smashwilson** [comment]
In Gophercloud, we have a centralized "make a request function" that just has a handler for 403s that attempts to re-auth with a new token. I'm not sure how difficult it would be to do globally with the Carina client.

**Comment by rgbkrk** [comment]
> In Gophercloud, we have a centralized "make a request function" that just has a handler for 403s that attempts to re-auth with a new token. I'm not sure how difficult it would be to do globally with the Carina client.

The answer to that ends up being that we also end up needing to have the tenant ID, which we don't have (without making other calls) as well as the fact that this isn't a proper `ServiceClient` for use with reauth.

**Comment by smashwilson** [comment]
Yeah... we capture most things like that by storing a closure in the `ServiceClient`, I recall. Of course that doesn't work across CLI invocations...

**Pull request merged**
