### PR TITLE
Update chocolatey package with new download url

### PR DESCRIPTION
**Pull request by carolynvs**
The Chocolatey gods have approved the `carina` package! 

I have updated the script which makes the chocolatey package with the new download url. This script is [run automatically on commits to master](http://build.openstacknetsdk.org/browse/RAX-CARINA), checks for a new version and publishes it to chocolatey.org.

### CODE REVIEW

**Comment by carolynvs** [comment]
Merge like no one is watching! :eyes:

**Comment by rgbkrk** [comment]
OMG YES!

**Comment by carolynvs** [comment]
So... I didn't know this but they moderate every single package version. v0.5.1 was just approved and is visible but 1.0.0 is in moderation now.

I talked with the choco gods and they have 1/2 of the moderation process automated and the last 1/2 is almost there. He manually approved a few packages for me but really until it's 100% automated, I wouldn't recommend our users try chocolatey for carina as they will always be behind. :cry:

**Comment by rgbkrk** [comment]
Lame. Wish it was like the [moderation of `carina` on homebrew](https://github.com/Homebrew/homebrew/pulls?q=is%3Apr+carina).

**Comment by carolynvs** [comment]
Dang, yeah that would be nice! It never was moderated before, and things were just fine. In fact, nuget.org is still unmoderated... I am hopeful that once they get their automation figured out it won't be months to get a version through moderation because it's pretty darn unusable right now...

**Comment by funkytaco** [comment]
Side note:
Might wanna put `brew update` in the README as I almost forgot you need to do that with Homebrew.

**Pull request merged**
